### ISSUE TITLE
Flaw in setup.py

### ISSUE THREAD

**Issue by baerbock** [azavea/raster-vision#665] opened 2019-01-22 00:05 UTC
`error in rastervision setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.`

**Comment by ddobre** [comment] 2019-01-23 00:17
I got around this by deleting the line pertaining to `feature-extraction` in `extras_requirements.json`.

**Comment by jamesmcclain** [comment] 2019-01-23 19:10
We created a temporary fix for this in https://github.com/azavea/raster-vision/pull/666, we need a permanent fix.

**Comment by jamesmcclain** [comment] 2019-03-26 17:35
This caused by the fact that the [unpublished feature extraction package](https://github.com/azavea/raster-vision/blob/d68dc1ac62bddf222f082a51d31c989485ca0294/extras_requirements.json#L15) does not conform to the required format.  There are three options:

a) Promote the temporary fix to a permanent fix
b) Remove the feature extraction package
c) Publish the incomplete feature extraction package

Options are given in my order of preference.

**Comment by lewfish** [comment] 2019-03-26 17:43
> Options are given in my order of preference.

Is the order descending or ascending?

**Comment by jamesmcclain** [comment] 2019-03-26 17:44
> > Options are given in my order of preference.
> 
> Is the order descending or ascending?

Descending.

**Comment by lewfish** [comment] 2019-03-26 17:59
With option a, when someone tries to install RV using pip, it won't install mask-to-polygon. Do you want to avoid c because it's a pain to publish to PyPi every time we update the library?

**Comment by lewfish** [comment] 2019-03-26 19:55
A good compromise (which was Rob's idea) is to follow option a except when we're about to make a release. In that case, we can make a release for `mask_to_polygon`, use the pip version in `extra_requirements.json` and uncomment [the line that removes it](https://github.com/jamesmcclain/raster-vision/blob/0d37a99bcc6190cb74115aa20904a111c01f4283/setup.py#L37). that way `mask_to_polygon` will get installed when someone pip install rastervision.

**Closed** 2019-03-28 17:20 UTC
Labels: review
