### ISSUE TITLE
Error loading model using Predictor

### ISSUE THREAD

**Issue by smohiudd** [azavea/raster-vision#1052] opened 2020-11-26 19:47 UTC
I'm using v0.12 via docker.  I want to pre-load a model so I can do multiple predictions quickly. 

When I use the `Predictor` class to load the model similar to what is done in `rastervision/core/cli.py`:

``` python 
model_path = "./model-bundle.zip"

with rv_config.get_tmp_dir() as tmp_dir:
    model = Predictor("./model-bundle.zip", tmp_dir)
```
or if I do this:

``` python 
model_path = "./model-bundle.zip"
tmp_dir = "./model_tmp"

model = Predictor("./model-bundle.zip", tmp_dir)
```
I get the following error:

```sh
ConfigError: The plugin_versions field contains an unrecognized plugin name: rastervision.core.
```

Predictions work fine when I use the cli but when I try to use the `Predictor` class myself, I get an error.

**Comment by lewfish** [comment] 2020-12-02 01:05
I've confirmed that this problem occurs on the `0.12` and `master` branches with the ISPRS example model bundle when I put the following script in the `rastervision/core` directory. I noticed that at the point where the script crashes, the registry does not contain any of the stuff contributed by the `rastervision.core` plugin. However, when I place the script in `/opt/src`, it does not crash. For now, I would say this is a workaround, but it does seem like there's something wonky going on with the registry.

```
from rastervision.pipeline import rv_config
from rastervision.core.predictor import Predictor

model_path = '/opt/data/raster-vision/0.12/model-zoo-0.12/isprs-potsdam-ss/model-bundle.zip'

with rv_config.get_tmp_dir() as tmp_dir:
    model = Predictor(model_path, tmp_dir)
```

**Comment by AwayFromTheMountains** [comment] 2021-09-07 07:26
Hello, I've found RasterVision really helpful, but I've got to the point where I need to run inference on thousands of images and I can't find a way round this bug. Running a script similar to the one above in /opt/src is not working for me; it just returns the same error about plugin_versions. Can you suggest any other workarounds?

**Comment by AdeelH** [comment] 2021-09-08 11:49
>Hello, I've found RasterVision really helpful, but I've got to the point where I need to run inference on thousands of images and I can't find a way round this bug. Running a script similar to the one above in /opt/src is not working for me; it just returns the same error about plugin_versions. Can you suggest any other workarounds?
I'm using pytorch-0.13 via Docker, although I've also tried pytorch-latest and encounter the same problem.

I was not able to reproduce this in a local build of the current master branch. I ran @lewfish's script above in `/opt/src/`.

Can you
- Ty pulling the latest version of pytorch-latest and try running this again?
- Share the output of running `rastervision --help` on the command line inside the Docker container?

**Comment by AwayFromTheMountains** [comment] 2021-09-09 10:42
Sure. Here is the output of running rastervision --help:

root@3f624ccf8c31:/opt/src# rastervision --help
Usage: python -m rastervision.pipeline.cli [OPTIONS] COMMAND [ARGS]...

  The main click command.

  Sets the profile, verbosity, and tmp_dir in RVConfig.

Options:
  -p, --profile TEXT  Sets the configuration profile name to use.
  -v, --verbose       Increment the verbosity level.  [x>=0]
  --tmpdir TEXT       Root of temporary directories to use.
  --help              Show this message and exit.

Commands:
  predict      Use a model bundle to predict on new images.
  run          Run sequence of commands within pipeline(s).
  run_command  Run an individual command within a pipeline.

**Comment by yddcode** [comment] 2021-12-03 03:23
Yes, What should I do when I want to predict multiple images? using ''rastervision predict command'' or other method?

**Comment by AdeelH** [comment] 2022-07-08 12:54
@yashgharat please share the script you're using and the full stack trace of the error.

**Comment by AdeelH** [comment] 2022-07-11 14:59
@yashgharat, thanks for providing the script. I was able to reproduce the error on both the 0.13 image as well as the latest image.

I will look further into this later but it seems to be an import order bug and seems to be fixed by adding `import rastervision.pipeline` as the first rastervision import.

**Closed** 2022-08-05 10:33 UTC
Labels: bug
