### ISSUE TITLE
GPU memory 

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1408] opened 2022-05-24 04:31 UTC
i'm running rv 0.12. in object detection my batch size is 1 and chip size is 300 when i run predict command it will occupied 1.7 gb in gpu but when i change chip size to 500 or 1000 it will occupied same 1.7 gb in gpu so how chip will store in gpu? can you help me regarding this? 
How this chip will occupied memory in gpu?

is it possible that i change some settings and my gpu itilization will be high and can reduce prediction time ?

**Comment by sagar1899** [comment] 2022-05-25 11:06
Can you help me?

**Comment by AdeelH** [comment] 2022-05-30 10:48
Duplicate of #1410

**Closed by AdeelH** 2022-05-30 10:48 UTC
